backend:
  name: git-gateway
  branch: main

media_folder: "public/fotos"
public_folder: "/fotos"

collections:
  - name: "productos"
    label: "Productos"
    folder: "content/productos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Imagen", name: "image", widget: "image"}
      - {label: "Orden", name: "order", widget: "number"}
      - {label: "Activo", name: "active", widget: "boolean", default: true} 