backend:
  name: git-gateway
  branch: main

media_folder: "public/fotos"
public_folder: "/fotos"

collections:
  - name: "hero"
    label: "Hero Section"
    files:
      - name: "home_hero"
        label: "Home Hero"
        file: "content/hero/home.json"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Subtítulo", name: "subtitle", widget: "string"}

  - name: "about"
    label: "Sobre Nosotros"
    files:
      - name: "about_section"
        label: "Sección Sobre Nosotros"
        file: "content/about/main.json"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Descripción", name: "description", widget: "text"}
          - {label: "Imagen", name: "image", widget: "image"}

  - name: "productos"
    label: "Productos"
    folder: "content/productos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Imagen", name: "image", widget: "image"}
      - {label: "Orden", name: "order", widget: "number"}
      - {label: "Activo", name: "active", widget: "boolean", default: true} 